name: Build and Release Executable

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure with CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Archive executable
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: build/Release/main.exe  # Adjust the path to your executable if different
